### PR TITLE
Suspend Windows when Linux is suspending

### LINKED ISSUE #26: Suspend guest when the host sleeps
One big issue is that Windows really doesn't like it when you just suspend the host and usually/always crashes.

For systemd users we can just use a sleep inhibitor ([this mess](https://gist.github.com/main--/f72663801f66420f31597277130e0612) shows how to do it).

Supporting bare pm-utils for non-systemd users is nice to have as well.

In any case, I believe this needs guest agent support.

### PR DESCRIPTION
**Pull request by oberien**
Fix #26

### CODE REVIEW

File: misc/windows-gaming.sh [hunk 1]
```diff
@@ -0,0 +1,24 @@
+#!/bin/sh
+
+# This needs to be located in /usr/lib/systemd/system-sleep/
```
Comment (main--) [inline misc/windows-gaming.sh]: Quoting `systemd-suspend(8)`:

>Note that scripts or binaries dropped in /usr/lib/systemd/system-sleep/ are intended for local use only and should be considered hacks. If applications want to be notified of system suspend/hibernation and resume, there are much nicer interfaces available.

As I explained in the issue, a sleep inhibitor is pretty definitely what we want here.

File: guest-agent/VfioService/VfioService/ClientManager.cs [hunk 2]
```diff
@@ -47,6 +48,9 @@ public ClientManager(MainForm mainForm)
                     case CommandIn.ReleaseModifiers:
                         StuckKeyFix.ReleaseModifiers();
                         break;
+                    case CommandIn.Suspend:
+                        Application.SetSuspendState(PowerState.Suspend, true, true);
```
Comment (main--) [inline guest-agent/VfioService/VfioService/ClientManager.cs]: Why are these flags correct? Isn't `false, false` a better choice in our case?

File: misc/windows-gaming.sh [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+  if [ -z "$nc" ]; then
+    nc=$(command -v ncat)
+  fi
+  if [ -z "$nc" ]; then
+    echo "No netcat, nc or ncat found. Exiting..."
+    exit 1
+  fi
+  # Currently on arch netcat has a bug where it does not end the connection.
+  # Therefore we use a timeout of 3 seconds.
+  echo -ne "\x05" | $nc -w 3 -U /run/user/1000/windows-gaming-driver/control.sock
```
Comment (main--) [inline misc/windows-gaming.sh]: The solution for this is the `-N` flag as the server will obviously keep waiting for additional commands until the client closes the connection. (I believe the default behavior of arch's openbsd-netcat changed in a recent update so we now have to specify it but previously didn't.)

File: misc/windows-gaming.sh [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+  # We don't know how long windows needs to suspend, so just wait 8 secnods for now,
+  # which is "good enough for my case".
+  # TODO: Fix this once #67 is fixed
```
Comment (main--) [inline misc/windows-gaming.sh]: Again, a sleep inhibitor does not have this issue as it it runs inside the driver and can simply react to the qapi event.

**Review by main-- — CHANGES_REQUESTED** [review]
I really think we need a sleep inhibitor.

Rest is looking great though.

**Review by main-- — APPROVED** [review]
