### PR TITLE
Dawn of the vfio 2.0 episode 2 reborn global offensive infinte u vite a new hope remastered enhanced edition rebooted electric boogaloo on new tides

### LINKED ISSUE #84: (Non)Critical Tasks
Before switching to tokio / futures / mio, we had the structure of Pollables being separated into non-critical tasks, meaning they can die without any further implication, and critical tasks, which would end the whole application if one fails or all end successfully.
With tokio, we can achieve the same by spawning non-critical tasks into a `Handle` and joining all criticals tasks into a single future which is executed with `Core::run`.

### LINKED ISSUE #105: Rework everything
Things are simple, really.

# VFIO 2.0 Episode 2 Reborn: Global Offensive Infinite U Vita

To pass through a generic PCI device into the VM, we need to take care of:

## IOMMU grouping

Simple to check in sysfs as soon as iommu is enabled. Ignore PCI bridges (maybe figure out why?) but make sure we're passing everything else, no exceptions.

## Resetting

* Device supports resetting: Easy. Just run vfio-bind on startup and bind back to the old driver on exit.
* Device is a GPU (and thus doesn't support resetting): Need to bind in initrd, before any other driver can mess with the device. Rest should be fine?
* Device is not a GPU but still doesn't support resetting: In theory there is no reason why this shouldn't "just work (tm)" if we bind on boot, like GPU (since GPU doesn't support resetting either and that works just fine). Arch wiki however says that you're fucked in this case and the qemu hangs forever on shutdown. TODO: Figure out if they're right. In any case, blacklisting builtin drivers (like xhci) is hard.

## Bind the device

The easy part: Look at what devices we have and translate that into qemu parameters.

## Simplify the world

Just learn more about vfio-pci and device binding in general - we might be able to work without kernel parameters or without these weird config changes. The tool as it is today only replicates a setup that worked for me once, it does not try very hard at being robust or elegant.

## vfio-bind

New tool: suid binary that rebinds all resettable PCI devices from the config to vfio-pci via the simple sysfs trick (modern version):

```sh
echo vfio-pci > /sys/bus/pci/devices/0000\:04\:00.0/driver_override
echo '0000:04:00.0' > /sys/bus/pci/devices/0000\:04\:00.0/driver/unbind
echo '0000:04:00.0' > /sys/bus/pci/drivers_probe
```

### PR DESCRIPTION
**Pull request by Ediacarium**
Fixes #105 

Closes #84 (obsolete then)

### CODE REVIEW

File: vfio-ubind/src/main.rs [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+use users::{get_user_by_uid, get_effective_uid, get_current_uid, get_group_by_name};
+use users::os::unix::GroupExt;
+
+fn pretty_write(path: &Path, content : &str, dryrun: bool) {
+	if dryrun {
+		println!("writing {} into {}", content, path.display());
+	} else { 
+		info!("writing {} into {}", content, path.display());
+	
+		let mut file = OpenOptions::new().write(true).open(&path).expect(&format!("Failed to open {}", path.display()));
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: `File::create`?

File: vfio-ubind/src/main.rs [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+extern crate env_logger;
+extern crate regex;
+extern crate users;
+
+use std::path::Path;
+use regex::Regex;
+use argparse::{ArgumentParser, StoreTrue, Store};
+use std::fs::{OpenOptions, read_link};
+use std::io::prelude::*;
+use users::{get_user_by_uid, get_effective_uid, get_current_uid, get_group_by_name};
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: Please don't import functions by-name, but use them with their module prefix: `users::get_user_by_uid`

File: vfio-ubind/src/main.rs [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+	
+	if get_effective_uid() != 0 {
+		error!("This tool has no root permission. Is the setuid bit not set or do you need to execute this as root?");
+	}
+	if get_current_uid() != 0 {
+		let vfio_group = get_group_by_name("vfio").expect("Your system has no vfio group. You need to be part of it to run this tool!");
+		let user = get_user_by_uid(get_current_uid()).unwrap();
+		let user_name = user.name();
+		
+		if let None = vfio_group.members().iter().position(|gm| gm == user_name) {
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: `if !foo.any(condition)`

File: vfio-ubind/src/main.rs [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+	
+	if !dbdf_regex.is_match(&device) {
+		if !bdf_regex.is_match(&device) {
+			println!("Please supply Domain:Bus:Device.Function of PCI device in form: dddd:bb:dd.f");
+			return;
+		} else {
+			warn!("No PCI domain supplied, assuming PCI domain is 0000");
+			device = "0000:".to_string() + &device;
+		}
+	}
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: `if !dbdf_regex.is_match(&device) && !bdf_regex.is_match(&device) { ... } else { ... }`

File: vfio-ubind/src/main.rs [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+		info!("File {} didn't exist", dev_iommu.display());
+		return;
+	}
+	
+	let dev_reset = dev_sysfs.join("reset");
+	
+	if ! dev_reset.exists() {
+		error!("The device does no support resetting!");
+		info!("File {} didn't exist", dev_reset.display());
+		return;
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: This is an error. Shouldn't we panic instead of exiting without error code?

File: windows-gaming-driver/src/config.rs [hunk 6]
```diff
@@ -241,6 +241,21 @@ pub struct StorageDevice {
 }
 
 #[derive(Deserialize, Serialize, Debug, Clone)]
+pub enum VfioDevice {
+	Permanent(String),
+	Temporarily(String)
```
Comment (oberien) [inline windows-gaming-driver/src/config.rs]: If you call it `Permanent`, it should be called `Temporary`.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 7]
```diff
@@ -25,9 +30,11 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
         println!();
     }
 
-    gpu::select(setup, machine).expect("Failed to select GPU");
+    select(setup, machine).expect("Failed to select PCI Devices");
     println!("Success!");
     println!();
+    
+    println!("");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: No need for the empty line above the print and the empty string inside `println! `

File: windows-gaming-driver/src/driver/qemu.rs [hunk 8]
```diff
@@ -113,7 +113,24 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
...
 
     for slot in cfg.machine.vfio_slots.iter() {
-        qemu.args(&["-device", &format!("vfio-pci,host={},multifunction=on", slot)]);
+    	let vfio_device = match slot {
+			&VfioDevice::Temporarily(ref device) => {
+				let mut child = Command::new(Path::new(::DATA_FOLDER).join("vfio-ubind")).arg(device).spawn().expect("failed to run vfio-ubind");
+				match child.wait() {
+					Ok(status) => 
+						if !status.success() {	
+						error!("vfio-ubind failed with {}! The device might not be bound to the vfio-driver and therefor not functional", status);
```
Comment (oberien) [inline windows-gaming-driver/src/driver/qemu.rs]: "and therefore not function correctly"

File: windows-gaming-driver/src/config.rs [hunk 9]
```diff
@@ -241,6 +241,21 @@ pub struct StorageDevice {
...
+}
+
+impl Display for VfioDevice {
+    fn fmt(&self, f: &mut Formatter) -> FmtResult {
+        f.write_str(match self {
+            &VfioDevice::Permanent(_) => "Permanent",
+            &VfioDevice::Temporarily(_) => "Temporarily",
```
Comment (oberien) [inline windows-gaming-driver/src/config.rs]: ~

File: windows-gaming-driver/src/driver/mod.rs [hunk 10]
```diff
@@ -96,10 +97,22 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
...
+    for slot in cfg.machine.vfio_slots.iter() {
+		if let &VfioDevice::Temporarily(ref device) = slot {
+			let mut child = Command::new(Path::new(::DATA_FOLDER).join("vfio-ubind")).arg(device).arg("-r").spawn().expect("failed to run vfio-ubind");
+			match child.wait() {
+				Ok(status) => 
+						if !status.success() {	
+						error!("vfio-ubind failed with {}! The device might still be bound to the vfio-driver!", status);
+						},
+				Err(err) => error!("failed to wait on child. Got: {}", err)
+
```
Comment (oberien) [inline windows-gaming-driver/src/driver/mod.rs]: unnecessary empty line

File: windows-gaming-driver/src/driver/mod.rs [hunk 11]
```diff
@@ -96,10 +97,22 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
...
+			match child.wait() {
+				Ok(status) => 
+						if !status.success() {	
+						error!("vfio-ubind failed with {}! The device might still be bound to the vfio-driver!", status);
+						},
+				Err(err) => error!("failed to wait on child. Got: {}", err)
+				
+			}
+		}
+	}
```
Comment (oberien) [inline windows-gaming-driver/src/driver/mod.rs]: The chance that we panic is pretty high. If we do panic during `core.run`, this cleanup code is not executed. Is it possible that you create a struct, which executes this code in the `Drop` implementation, so it'll be executed when unwinding?

File: windows-gaming-driver/src/driver/qemu.rs [hunk 12]
```diff
@@ -113,7 +113,24 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
...
+						},
+					Err(err) => error!("failed to wait on child. Got: {}", err)
+
```
Comment (oberien) [inline windows-gaming-driver/src/driver/qemu.rs]: unneseccary empty line

File: windows-gaming-driver/src/driver/qemu.rs [hunk 13]
```diff
@@ -113,7 +113,24 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
...
+						if !status.success() {	
+						error!("vfio-ubind failed with {}! The device might not be bound to the vfio-driver and therefor not functional", status);
+						},
+					Err(err) => error!("failed to wait on child. Got: {}", err)
+					
+				}
+				device
+			}
+    		&VfioDevice::Permanent(ref device) => 
+    			device
```
Comment (oberien) [inline windows-gaming-driver/src/driver/qemu.rs]: Can be in the above line behind `=>`

File: windows-gaming-driver/src/setup/vfio.rs [hunk 14]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+    let udev = Context::new().expect("Failed to create udev context");
+    let mut iter = Enumerator::new(&udev)?;
+    iter.match_subsystem("pci")?;
+    let pci_devs: Vec<_> = iter.scan_devices()?.map(PciDevice::new).collect();
+
+    
+	// filter to the display controller class (0x03XXXX, udev drops the leading zero)
+	let (gpu_devices, gpu_dev_ids, pci_devs) = ask_selection("Which graphics card do you want to pass through?", &|x| x.pci_class.starts_with("3") && x.pci_class.len() == 5, pci_devs, true);
+	
+	println!("Add aditional  pci devices(1/2)");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: One space in the middle too much, one between "devices" and the opening parethesis too less.

File: windows-gaming-driver/src/util.rs [hunk 15]
```diff
@@ -23,3 +23,23 @@ pub fn usable_ports(bus: UsbBus) -> usize {
...
+impl<T> PrettySplit<T> for Vec<T> {
+	fn into_two(self, filter: &Fn(&T) -> (bool) ) -> (Vec<T>, Vec<T>){
+		let mut matched = Vec::new();
+		let mut remaining = Vec::new();
+	
+		for dev in self {
+			if filter(&dev) {
+				matched.push(dev);
+			}
+			else {
```
Comment (oberien) [inline windows-gaming-driver/src/util.rs]: welp

File: windows-gaming-driver/src/setup/vfio.rs [hunk 16]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+	println!();
+	println!("Please choose aditional pci devices. These will be passed throught to qemu on boot.");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "through"

File: windows-gaming-driver/src/setup/vfio.rs [hunk 17]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+    	return (Vec::new(), Vec::new(), devices);
+    }
+    let selected = devices.remove(selection);
+
+	devices.extend(remaining_pci_devices);
+	
+	let (mut related_devices, unpassed_pci_devices) = devices.into_two(&|dev| dev.pci_device() == selected.pci_device());
+	related_devices.push(selected);
+	
+	let (mut ret_devices, mut ret_devids, ret_pci_devices) = ask_selection(question, filter, unpassed_pci_devices, permanent);
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: Recursion instead of a loop? That never ended well…

File: windows-gaming-driver/src/setup/vfio.rs [hunk 18]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+
+    
+	// filter to the display controller class (0x03XXXX, udev drops the leading zero)
+	let (gpu_devices, gpu_dev_ids, pci_devs) = ask_selection("Which graphics card do you want to pass through?", &|x| x.pci_class.starts_with("3") && x.pci_class.len() == 5, pci_devs, true);
+	
+	println!("Add aditional  pci devices(1/2)");
+	println!();
+	println!("Please choose aditional pci devices. These will be passed throught to qemu on boot.");
+	println!("NOTE: The devices listed here can be reset. They will be bound to the vfio-pci driver on qemu's start and unbound when it quits");
+	println!("This should usually work. If it doesn't ur on ur own.");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: We should be formal and not super colloquial :)

File: windows-gaming-driver/src/setup/vfio.rs [hunk 19]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+	println!("You will not be able to use these devices while qemu is running.");
+	println!("If the device you want to pass through is not resettable it will show up in the next step.");
+	println!("If you want a device permanently bound to vfio-pci for some reason select it in the next step.");
+	println!("MAKE SURE YOU DON'T PASS THROUGH YOUR USB-CONTROLLER TO WHICH YOUR KEYBOARD AND MOUSE IS CONNECTED!");
+	println!("Helpful tools to avoid this and figure out which numbers are what devices are lspci and lsusb with the -v, -t (lsusb only) and -nn (lspci only) command.");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "which numbers are which devices"

File: windows-gaming-driver/src/setup/vfio.rs [hunk 20]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+	println!();
+	let (temp_devices, _, pci_devs) = ask_selection("Which PCI Devices do you want to pass through temporarily?", &|x| Path::new(PCI_DEVS_PATH).join(x.pci_slot.clone()).join("reset").exists(), pci_devs, false);
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "would you like to"

File: windows-gaming-driver/src/setup/vfio.rs [hunk 21]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+	println!("Add aditional pci devices(2/2)");
+	println!("");
+	println!("If you don't know what you are doing, chose None here!");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: choose

File: windows-gaming-driver/src/setup/vfio.rs [hunk 22]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+	println!("NOTE: EVERY PCI DEVICE LISTED HERE WILL BE PERMANENTLY BOUND TO VFIO-PCI!");
+	println!("ONLY ADD DEVICES HERE IF YOU KNOW WHAT YOU ARE DOING!");
+	println!("If you kill your system using this there is only one thing i can say to you:");
+	println!();
+	println!("U done goofed m8.");
+	println!("Ur on ur own :)");
+	println!();
+	//filter to everything except the PCI Bridges
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: Space between the comment-slashes and the content to make it more distiguishable from outcommented code.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 23]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+	let (perm_devices, perm_dev_ids, _) = ask_selection("Which PCI Device do you want to pass through permanently?", &|x| x.pci_class != "60400", pci_devs, true);
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "would you like to"

File: windows-gaming-driver/src/setup/vfio.rs [hunk 24]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
 
+fn select(setup: &mut SetupConfig, machine: &mut MachineConfig) -> Result<()> {
+    let udev = Context::new().expect("Failed to create udev context");
+    let mut iter = Enumerator::new(&udev)?;
+    iter.match_subsystem("pci")?;
+    let pci_devs: Vec<_> = iter.scan_devices()?.map(PciDevice::new).collect();
+
+    
+	// filter to the display controller class (0x03XXXX, udev drops the leading zero)
+	let (gpu_devices, gpu_dev_ids, pci_devs) = ask_selection("Which graphics card do you want to pass through?", &|x| x.pci_class.starts_with("3") && x.pci_class.len() == 5, pci_devs, true);
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "would you like to"

**Review by oberien — CHANGES_REQUESTED** [review]
¡4 spaces, not tabs!

File: vfio-ubind/src/main.rs (hunk 1 above)
Comment (main--) [reply vfio-ubind/src/main.rs]: Not 100% equivalent:

>This function will create a file if it does not exist, and will truncate it if it does.

We don't really care about the truncation aspect but we definitely don't want to try to create random files in sysfs (not like it would work anyways but it doesn't make sense to even try).

File: windows-gaming-driver/src/driver/mod.rs (hunk 11 above)
Comment (main--) [reply windows-gaming-driver/src/driver/mod.rs]: >The chance that we panic is pretty high.

Is it? If so, why? Note that this was restructured to no longer panic when an error is returned.

File: Makefile [hunk 25]
```diff
@@ -14,6 +15,9 @@ test:
 $(DRIVER):
 	cd windows-gaming-driver && cargo build --release --locked
 
+$(VFIO_UBIND):
+	cd vfio-ubind && cargo build --release --locked
```
Comment (main--) [inline Makefile:19]: Consider using a cargo workspace for all our rust stuff.

(not 100% if that's the right solution for our case but I think it might be)

File: vfio-ubind/src/main.rs [hunk 26]
```diff
@@ -0,0 +1,112 @@
...
+use regex::Regex;
+use argparse::{ArgumentParser, StoreTrue, Store};
+use std::fs::{OpenOptions, read_link};
+use std::io::prelude::*;
+use users::{get_user_by_uid, get_effective_uid, get_current_uid, get_group_by_name};
+use users::os::unix::GroupExt;
+
+fn pretty_write(path: &Path, content : &str, dryrun: bool) {
+	if dryrun {
+		println!("writing {} into {}", content, path.display());
```
Comment (main--) [inline vfio-ubind/src/main.rs]: I have never seen dry-run affecting the actual semantics and I don't see why it ever should. If you actually are stupid enough to do dry-run with logging disabled, that's your problem.

File: vfio-ubind/src/main.rs [hunk 27]
```diff
@@ -0,0 +1,112 @@
...
+	let mut device = "".to_string();
+	
+	{
+		let mut ap = ArgumentParser::new();
+		ap.set_description("This tool allows you to bind the vfio driver to a specified resetable pci-device");
+		ap.refer(&mut device).add_argument("PCI-Device", Store, "The PCI-Device to bind to").required();
+		ap.refer(&mut dryrun).add_option(&["-d", "--dry-run"], StoreTrue, "Don't change anything");
+		ap.refer(&mut remove).add_option(&["-r", "--remove"], StoreTrue, "Reattach the default Driver to the device");
+		ap.parse_args_or_exit();
+	}
```
Comment (main--) [inline vfio-ubind/src/main.rs]: :+1:

File: windows-gaming-driver/src/driver/mod.rs (hunk 11 above)
Comment (oberien) [reply windows-gaming-driver/src/driver/mod.rs]: At least I always get something like `thread 'main' panicked at 'Unexpected error: Connection reset by peer (os error 104)', src/driver/mod.rs:101` when I shutdown Windows.

File: vfio-ubind/src/main.rs [hunk 28]
```diff
@@ -0,0 +1,112 @@
...
+	
+	env_logger::init().unwrap();
+	
+	info!("effective uid: {} current uid: {}", get_effective_uid(), get_current_uid());
```
Comment (main--) [inline vfio-ubind/src/main.rs]: Consider downgrading this to debug

update: you seem to be relying on the fact that info is not displayed by default (thus using it as something like debug). in that case it's fine

File: vfio-ubind/src/main.rs [hunk 29]
```diff
@@ -0,0 +1,112 @@
...
+	
+	if get_effective_uid() != 0 {
+		error!("This tool has no root permission. Is the setuid bit not set or do you need to execute this as root?");
```
Comment (main--) [inline vfio-ubind/src/main.rs]: >Is the setuid bit not set or do you need to execute this as root?

This doesn't really make sense. How about: "This tool requires root permissions. If the setuid bit is not set, you need to execute this as root!"

File: vfio-ubind/src/main.rs [hunk 30]
```diff
@@ -0,0 +1,112 @@
...
+			panic!("You're not part of the vfio group. Apply there and run this tool again!");
+		}
+		else {
+			debug!("User is part of the vfio group...continuing");
+		}
+	}
+
+	debug!("Checking with Regexes");
+	let dbdf_regex = Regex::new(r"^[[:xdigit:]]{4}:[[:xdigit:]]{2}:[[:xdigit:]]{2}.[[:xdigit:]]$").unwrap();
+	let bdf_regex = Regex::new(r"^[[:xdigit:]]{2}:[[:xdigit:]]{2}.[[:xdigit:]]$").unwrap();
```
Comment (main--) [inline vfio-ubind/src/main.rs]: I remain convinced that using regexes here is a bad idea. The entire reason why this is a separate binary is that we want to avoid giving full root access 20 untrusted libraries, so we should only use what we really need. From that perspective log+env_logger are already hard to justify but at least they are useful (debugging).

Regexes however give you nothing at all (as we discussed), you get the exact same behavior with something like this:

```rust
if device[2] == ':' {
    "0000:".to_owned() + device
} else {
    device
}
```

The important point here is that you're not actually using the regexes at all (to get their captured values). You are only checking if they match or not. But the system already implicitly does that for you because the sysfs folder won't exist if the ID is invalid.

File: vfio-ubind/src/main.rs [hunk 31]
```diff
@@ -0,0 +1,112 @@
...
+		} else {
+			warn!("No PCI domain supplied, assuming PCI domain is 0000");
+			device = "0000:".to_string() + &device;
+		}
+	}
+	
+	let dev_sysfs = Path::new("/sys/bus/pci/devices/").join(&device);
+	let dev_iommu = dev_sysfs.join("iommu");
+	
+	if !dev_iommu.exists() {
```
Comment (main--) [inline vfio-ubind/src/main.rs]: This check is not necessary. While rebinding devices to vfio-pci is not very useful when iommu is off, I don't see any reason to prohibit it. Again, **this binary is not user-facing**!

File: vfio-ubind/src/main.rs [hunk 32]
```diff
@@ -0,0 +1,112 @@
...
+		println!("No signs of an IOMMU. Check your hardware and/or linux cmdline parameters.");
+		println!("Use intel_iommu=on or iommu=pt iommu=1");
+		info!("File {} didn't exist", dev_iommu.display());
+		return;
+	}
+	
+	let dev_reset = dev_sysfs.join("reset");
+	
+	if ! dev_reset.exists() {
```
Comment (main--) [inline vfio-ubind/src/main.rs]: stray space

File: vfio-ubind/src/main.rs [hunk 33]
```diff
@@ -0,0 +1,112 @@
...
+		if driver.file_name().unwrap() == "vfio-pci" && !remove{
+			println!("Device already bound to vfio-pci driver, nothing to do here");
+			return;
+		}
+		info!("Device already has a driver, unbinding");
+		
+		let driver = if remove {"\n"} else {"vfio-pci"};
+		pretty_write(&dev_sysfs.join("driver_override"), driver, dryrun);
+		pretty_write(&dev_sysfs.join("driver/unbind"), &device, dryrun);		
+	}
```
Comment (main--) [inline vfio-ubind/src/main.rs]:
```rust
} else if !remove {
    // must set this in this case as well
    pretty_write(&dev_sysfs.join("driver_override"), "vfio-pci", dryrun);
}
```

File: vfio-ubind/src/main.rs [hunk 34]
```diff
@@ -0,0 +1,112 @@
...
+
+use std::path::Path;
+use regex::Regex;
+use argparse::{ArgumentParser, StoreTrue, Store};
+use std::fs::{OpenOptions, read_link};
+use std::io::prelude::*;
+use users::{get_user_by_uid, get_effective_uid, get_current_uid, get_group_by_name};
+use users::os::unix::GroupExt;
+
+fn pretty_write(path: &Path, content : &str, dryrun: bool) {
```
Comment (main--) [inline vfio-ubind/src/main.rs]: Conventionally functions like this would be declared like this:

```rust
fn pretty_write<P: AsRef<Path>>(path: T, content: &str, dryrun: bool) {
```

This allows you to use `&Path` or `PathBuf` as parameter, depending on what you have.

(btw stray space in `content :`)

File: windows-gaming-driver/src/config.rs [hunk 35]
```diff
@@ -218,7 +218,7 @@ pub struct MachineConfig {
     pub threads: Option<u32>,
 
     // convention: gpu is first
-    pub vfio_slots: Vec<String>,
+    pub vfio_slots: Vec<VfioDevice>,
```
Comment (main--) [inline windows-gaming-driver/src/config.rs]: :+1: 

(perhaps renaming this would be a good idea though now that this describes entire devices and not just slots)

File: windows-gaming-driver/src/config.rs [hunk 36]
```diff
@@ -241,6 +241,21 @@ pub struct StorageDevice {
 }
 
 #[derive(Deserialize, Serialize, Debug, Clone)]
+pub enum VfioDevice {
```
Comment (main--) [inline windows-gaming-driver/src/config.rs]: I don't like this. How about:

```rust
struct VfioDevice {
    resettable: bool,
    slot: String,
    device: PciId,
}
```

(Device id is interesting anyways for the potential sanity checks on startup I mentioned. It also solves the issue where the setup section would store its own list of device IDs that can get out of sync/order with the slots in here)

File: windows-gaming-driver/src/config.rs (hunk 9 above)
Comment (main--) [inline windows-gaming-driver/src/config.rs]: This is not a useful `Display` impl.

File: windows-gaming-driver/src/driver/mod.rs [hunk 37]
```diff
@@ -17,12 +17,13 @@ use std::os::unix::net::{UnixListener as StdUnixListener};
 use std::fs::{self, Permissions};
 use std::os::unix::fs::PermissionsExt;
 use std::path::Path;
+use std::process::{Command};
```
Comment (main--) [inline windows-gaming-driver/src/driver/mod.rs]: Don't use braces if you're only importing one thing.

File: windows-gaming-driver/src/driver/mod.rs [hunk 38]
```diff
@@ -96,10 +97,22 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
...
     ]).map(|_| ());
 
-    match core.run(qemu.select(joined)) {
-        Ok(((), _)) => (), // one (*hopefully* qemu) is done, so the other is too
-        Err((e, _)) => panic!("Unexpected error: {}", e),
-    }
-
+    core.run(qemu.join(joined.or_else(|x| { error!("Unexpected error: {}", x); Ok(()) }))).expect("Unexpected error");
+
+	info!("unbinding resetable vfio-things");
```
Comment (main--) [inline windows-gaming-driver/src/driver/mod.rs]: typo: resettable

File: windows-gaming-driver/src/driver/mod.rs [hunk 39]
```diff
@@ -96,10 +97,22 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
...
+	
+    for slot in cfg.machine.vfio_slots.iter() {
+		if let &VfioDevice::Temporarily(ref device) = slot {
+			let mut child = Command::new(Path::new(::DATA_FOLDER).join("vfio-ubind")).arg(device).arg("-r").spawn().expect("failed to run vfio-ubind");
```
Comment (main--) [inline windows-gaming-driver/src/driver/mod.rs]: This function's `data` parameter is literally `Path::new(DATA_FOLDER)` (passed through from `main()`).

File: windows-gaming-driver/src/driver/mod.rs [hunk 40]
```diff
@@ -96,10 +97,22 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
...
+			match child.wait() {
```
Comment (main--) [inline windows-gaming-driver/src/driver/mod.rs]: I would just unwrap/expect here.

File: windows-gaming-driver/src/driver/qemu.rs [hunk 41]
```diff
@@ -113,7 +113,24 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
     qemu.args(&["-netdev", &usernet, "-device", "e1000,netdev=unet"]);
 
     for slot in cfg.machine.vfio_slots.iter() {
-        qemu.args(&["-device", &format!("vfio-pci,host={},multifunction=on", slot)]);
+    	let vfio_device = match slot {
+			&VfioDevice::Temporarily(ref device) => {
+				let mut child = Command::new(Path::new(::DATA_FOLDER).join("vfio-ubind")).arg(device).spawn().expect("failed to run vfio-ubind");
```
Comment (main--) [inline windows-gaming-driver/src/driver/qemu.rs]: ~

File: vfio-ubind/src/main.rs (hunk 4 above)
Comment (Ediacarium) [inline vfio-ubind/src/main.rs]: !dbdf_regex.is_match(&device) && !bdf_regex.is_match(&device) === true

File: windows-gaming-driver/src/driver/qemu.rs (hunk 13 above)
Comment (main--) [inline windows-gaming-driver/src/driver/qemu.rs]: A match where both arms return the same thing generally indicates that you're doing it wrong. But this is not really relevant since that thing sholdn't be an enum to begin with.

File: windows-gaming-driver/src/setup/vfio.rs (hunk 20 above)
Comment (main--) [inline windows-gaming-driver/src/setup/vfio.rs]: FYI udev devices have `syspath()`

this is very definitely the best way to access this path (check all the other udev code, that's why we don't have any existing "/sys/bus/pci" constants)

Now this *might* be hidden because we convert PCI devices to our own `PciDevice` struct but the fix in that case is to simply change `PciDevice` to carry the syspath.

File: vfio-ubind/src/main.rs [hunk 42]
```diff
@@ -0,0 +1,112 @@
...
+	}
+
+	debug!("Checking with Regexes");
+	let dbdf_regex = Regex::new(r"^[[:xdigit:]]{4}:[[:xdigit:]]{2}:[[:xdigit:]]{2}.[[:xdigit:]]$").unwrap();
+	let bdf_regex = Regex::new(r"^[[:xdigit:]]{2}:[[:xdigit:]]{2}.[[:xdigit:]]$").unwrap();
+	
+	if !dbdf_regex.is_match(&device) {
+		if !bdf_regex.is_match(&device) {
+			println!("Please supply Domain:Bus:Device.Function of PCI device in form: dddd:bb:dd.f");
+			return;
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: This is an error. Shouldn't we panic to to make that clear?

File: windows-gaming-driver/src/util.rs [hunk 43]
```diff
@@ -23,3 +23,23 @@ pub fn usable_ports(bus: UsbBus) -> usize {
     }
 }
 
+pub trait PrettySplit<T>{
+	fn into_two(self, &Fn(&T) -> (bool)) -> (Vec<T>, Vec<T>);
```
Comment (main--) [inline windows-gaming-driver/src/util.rs]: This already exists. It's called [partition](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.partition).

File: windows-gaming-driver/src/setup/vfio.rs (hunk 20 above)
Comment (main--) [reply windows-gaming-driver/src/setup/vfio.rs]: Actually come think of it, it's probably better to just check resettability in `PciDevice` directly.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 44]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+	all_devices.extend(temp_devices);
+	all_devices.extend(perm_devices);
+	
+	setup.vfio_devs = all_perm_device_ids;
+	machine.vfio_slots = all_devices;
+	
+    Ok(())	
+}
+
+fn ask_selection<'a>(question: &str, filter: &Fn(&PciDevice) -> (bool), pci_devices: Vec<PciDevice<'a>>, permanent: bool) -> (Vec<VfioDevice>, Vec<PciId>, Vec<PciDevice<'a>>) {
```
Comment (main--) [inline windows-gaming-driver/src/setup/vfio.rs]: Rename this to something like "select_devices". The current name feels more like a generic ask function that belongs into the `ask` module and it doesn't indicate at all that this function actually loops until all selections are done.

File: windows-gaming-driver/src/setup/vfio.rs (hunk 17 above)
Comment (main--) [reply windows-gaming-driver/src/setup/vfio.rs]: Seconded. The recursion makes this **very** hard to read and I'm pretty sure restructuring this to a loop is actually trivial, right?

File: windows-gaming-driver/src/setup/vfio.rs [hunk 45]
```diff
@@ -79,6 +86,93 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+	
+	let (mut related_devices, unpassed_pci_devices) = devices.into_two(&|dev| dev.pci_device() == selected.pci_device());
+	related_devices.push(selected);
+	
+	let (mut ret_devices, mut ret_devids, ret_pci_devices) = ask_selection(question, filter, unpassed_pci_devices, permanent);
+	ret_devices.extend(related_devices.iter().map(|dev| if permanent {VfioDevice::Permanent(dev.pci_slot.clone())} else {VfioDevice::Temporarily(dev.pci_slot.clone())}));
+	ret_devids.extend(related_devices.iter().map(|dev| dev.id));
+	
+	(ret_devices, ret_devids, ret_pci_devices)
+}
```
Comment (main--) [inline windows-gaming-driver/src/setup/vfio.rs]: Please restructure this.

What you're doing right now:

* Ask for GPUs (or literally anything else)
* Ask for resettable devices (or literally anything else)
* Ask for nonresettable devices (or literally anything else)

(it should be obvious why this is bad)

What you should be doing:

* Ask for a *single* GPU (or *nothing at all*)
* Ask if they would like to add other PCI devices
* Only if they answered yes, ask for any number of PCI devices (but straight up prohibit bridges because wtf) (Here, we can initially hide non-resettable devices and only show them if they specifically ask for it, but warn in that case)

**Review by main-- — CHANGES_REQUESTED** [review]

File: vfio-ubind/src/main.rs (hunk 1 above)
Comment (oberien) [reply vfio-ubind/src/main.rs]: Sounds like a valid point ;)

File: vfio-ubind/src/main.rs (hunk 34 above)
Comment (oberien) [reply vfio-ubind/src/main.rs]: It also allows `String`, `str`, `OsStr`, `OsString` and many other :)

File: windows-gaming-driver/src/driver/mod.rs (hunk 40 above)
Comment (Ediacarium) [reply windows-gaming-driver/src/driver/mod.rs]: If we unwrap/expect here, we skip trying to unbind the remaining devices.

File: windows-gaming-driver/src/setup/vfio.rs (hunk 18 above)
Comment (Ediacarium) [reply windows-gaming-driver/src/setup/vfio.rs]: As formal as this?
```
machine.memory = ask::anything("How much memory would you like to assign to it?",
                                       "be careful no validation LUL", |x| Some(x.to_owned()));
```
\- wm.rs ~line 67

File: vfio-ubind/src/main.rs [hunk 46]
```diff
@@ -65,14 +64,10 @@ fn main() {
...
-		if !bdf_regex.is_match(&device) {
-			println!("Please supply Domain:Bus:Device.Function of PCI device in form: dddd:bb:dd.f");
-			return;
-		} else {
-			warn!("No PCI domain supplied, assuming PCI domain is 0000");
-			device = "0000:".to_string() + &device;
-		}
+	match (dbdf_regex.is_match(&device), bdf_regex.is_match(&device)) {
+		(false, true) => {warn!("No PCI domain supplied, assuming PCI domain is 0000");	device = "0000:".to_string() + &device;},
+		(false, false) => {	panic!("Please supply Domain:Bus:Device.Function of PCI device in form: dddd:bb:dd.f");}
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: unnecessary tab between `{` and `panic`. In fact the whole block is not needed.

File: windows-gaming-driver/src/driver/qemu.rs [hunk 47]
```diff
@@ -112,26 +112,21 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
     trace!("setup usernet");
     qemu.args(&["-netdev", &usernet, "-device", "e1000,netdev=unet"]);
 
-    for slot in cfg.machine.vfio_slots.iter() {
-    	let vfio_device = match slot {
-			&VfioDevice::Temporarily(ref device) => {
-				let mut child = Command::new(Path::new(::DATA_FOLDER).join("vfio-ubind")).arg(device).spawn().expect("failed to run vfio-ubind");
+	//TODO: Check if the configured device is in the configured slot
```
Comment (oberien) [inline windows-gaming-driver/src/driver/qemu.rs]: Space between the comment-slashes and the content to make it more distiguishable from outcommented code.

File: vfio-ubind/src/main.rs [hunk 48]
```diff
@@ -43,17 +42,17 @@ fn main() {
...
-	if get_effective_uid() != 0 {
-		error!("This tool has no root permission. Is the setuid bit not set or do you need to execute this as root?");
+	if users::get_effective_uid() != 0 {
+		error!("This tool requires root permissions. If the setuid bit is not set, you need to execute this as root!");
 	}
-	if get_current_uid() != 0 {
-		let vfio_group = get_group_by_name("vfio").expect("Your system has no vfio group. You need to be part of it to run this tool!");
-		let user = get_user_by_uid(get_current_uid()).unwrap();
+	if users::get_current_uid() != 0 {
+		let vfio_group = users::get_group_by_name("vfio").expect("Your system has no vfio group. You need to be part of it to run this tool!");
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: Newline before `.expect`, otherwise the line is pretty damn long.

File: vfio-ubind/src/main.rs [hunk 49]
```diff
@@ -65,14 +64,10 @@ fn main() {
...
-	if !dbdf_regex.is_match(&device) {
-		if !bdf_regex.is_match(&device) {
-			println!("Please supply Domain:Bus:Device.Function of PCI device in form: dddd:bb:dd.f");
-			return;
-		} else {
-			warn!("No PCI domain supplied, assuming PCI domain is 0000");
-			device = "0000:".to_string() + &device;
-		}
+	match (dbdf_regex.is_match(&device), bdf_regex.is_match(&device)) {
+		(false, true) => {warn!("No PCI domain supplied, assuming PCI domain is 0000");	device = "0000:".to_string() + &device;},
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: Missing space between `{` and `warn`. Also if you open a block, put the content in new lines.

File: vfio-ubind/src/main.rs [hunk 50]
```diff
@@ -82,19 +77,18 @@ fn main() {
 		println!("No signs of an IOMMU. Check your hardware and/or linux cmdline parameters.");
 		println!("Use intel_iommu=on or iommu=pt iommu=1");
 		info!("File {} didn't exist", dev_iommu.display());
-		return;
+		panic!();
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: Please include the error message into the `panic` instead of printing it normally beforehand.

File: windows-gaming-driver/src/driver/mod.rs [hunk 51]
```diff
@@ -99,18 +99,17 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
...
-		if let &VfioDevice::Temporarily(ref device) = slot {
-			let mut child = Command::new(Path::new(::DATA_FOLDER).join("vfio-ubind")).arg(device).arg("-r").spawn().expect("failed to run vfio-ubind");
+    for dev in cfg.machine.vfio_slots.iter() {
+		if dev.resettable {
+			let mut child = Command::new(data.join("vfio-ubind")).arg(&dev.slot).arg("-r").spawn().expect("failed to run vfio-ubind");
 			match child.wait() {
 				Ok(status) => 
 						if !status.success() {	
 						error!("vfio-ubind failed with {}! The device might still be bound to the vfio-driver!", status);
 						},
```
Comment (oberien) [inline windows-gaming-driver/src/driver/mod.rs]: Use match guards here to include the if condition into the match arm. This does add a new match arm, but makes the code more readable.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 52]
```diff
@@ -91,84 +88,78 @@ fn select(setup: &mut SetupConfig, machine: &mut MachineConfig) -> Result<()> {
...
+		println!("Please choose aditional pci devices. These will be passed through to qemu on boot.");
+		println!("NOTE: The devices listed here can be reset. They will be bound to the vfio-pci driver on qemu's start and unbound when it quits");
+		println!("This should usually work. If it doesn't you're on your own.");
+		println!("You will not be able to use these devices while qemu is running.");
+		println!("If the device you want to pass through is not resettable (like a gpu) it will show up in the next step.");
+		println!("If you want a device permanently bound to vfio-pci for some reason select it in the next step.");
+		println!("MAKE SURE YOU DON'T PASS THROUGH YOUR USB-CONTROLLER TO WHICH YOUR KEYBOARD AND MOUSE IS CONNECTED!");
+		println!("Helpful tools to avoid this and figure out which numbers are which devices are lspci and lsusb with the -v, -t (lsusb only) and -nn (lspci only) command.");
+		println!();
+		let resetable_devices = pci_devs.iter().filter(|x| Path::new(PCI_DEVS_PATH).join(x.pci_slot.clone()).join("reset").exists()).collect();
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: You can check the `PciDevice.resettable` flag here.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 53]
```diff
@@ -91,84 +88,78 @@ fn select(setup: &mut SetupConfig, machine: &mut MachineConfig) -> Result<()> {
...
+	for (i, dev) in askable_devices.iter().enumerate() {
+	    println!("[{}]\t{}", i, dev);
+	}
+	println!("[{}]\tNone of the above.", askable_devices.len());
+
+	let selection = ask::numeric(question, 0..askable_devices.len()+1);
 	
-	(ret_devices, ret_devids, ret_pci_devices)
+	if selection < askable_devices.len() {
+		let ref selected = askable_devices[selection];
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: Does `let selected = &askable_devices[selection]` work here?

File: windows-gaming-driver/src/setup/vfio.rs [hunk 54]
```diff
@@ -91,84 +88,78 @@ fn select(setup: &mut SetupConfig, machine: &mut MachineConfig) -> Result<()> {
...
+		for device in pci_devs.iter().filter(|x| x.pci_device() == selected.pci_device()) {
+			let vfio_device = VfioDevice {
+				resettable: device.resettable,
+				slot: device.pci_slot.clone(),
+				device: device.id,
+			};
+			
+			if !device.resettable {
+				setup.vfio_devs.push(device.id);
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: Can't we iterate through `machine.vfio_slots` where we are currently using `setup.vfio_devs`?

**Review by oberien — CHANGES_REQUESTED** [review]
¡4 spaces instead of tabs!

File: windows-gaming-driver/src/setup/vfio.rs (hunk 54 above)
Comment (Ediacarium) [reply windows-gaming-driver/src/setup/vfio.rs]: In this code we can, however at least iommu.rs needs it later on.

You *could* argue that the vfio-module should just do the iommu checking directly instead of putting it into a different step, which could help, if you already have iommu enabled for some reason and we could've checked it when you first select the vfio-devices. But i think that is an entirely different issue.

File: vfio-ubind/src/main.rs [hunk 55]
```diff
@@ -65,19 +66,19 @@ fn main() {
     let bdf_regex = Regex::new(r"^[[:xdigit:]]{2}:[[:xdigit:]]{2}.[[:xdigit:]]$").unwrap();
     
     match (dbdf_regex.is_match(&device), bdf_regex.is_match(&device)) {
-        (false, true) => {warn!("No PCI domain supplied, assuming PCI domain is 0000");	device = "0000:".to_string() + &device;},
-        (false, false) => {	panic!("Please supply Domain:Bus:Device.Function of PCI device in form: dddd:bb:dd.f");}
+        (false, true) => { 
+            warn!("No PCI domain supplied, assuming PCI domain is 0000");	device = "0000:".to_string() + &device; },
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: really¿¿¿

File: vfio-ubind/src/main.rs [hunk 56]
```diff
@@ -65,19 +66,19 @@ fn main() {
...
+        (false, false) => {	
+            panic!("Please supply Domain:Bus:Device.Function of PCI device in form: dddd:bb:dd.f"); }
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: This still doesn't need a block.

File: vfio-ubind/src/main.rs [hunk 57]
```diff
@@ -65,19 +66,19 @@ fn main() {
...
     
     let dev_sysfs = Path::new("/sys/bus/pci/devices/").join(&device);
     let dev_iommu = dev_sysfs.join("iommu");
     
     if !dev_iommu.exists() {
-        println!("No signs of an IOMMU. Check your hardware and/or linux cmdline parameters.");
-        println!("Use intel_iommu=on or iommu=pt iommu=1");
         info!("File {} didn't exist", dev_iommu.display());
-        panic!();
+        panic!("No signs of an IOMMU. Check your hardware and/or linux cmdline parameters.Use intel_iommu=on or iommu=pt iommu=1");
```
Comment (oberien) [inline vfio-ubind/src/main.rs]: The line is too long. Maybe split the string into multiple lines.

File: windows-gaming-driver/src/driver/qemu.rs [hunk 58]
```diff
@@ -112,16 +112,15 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
...
         if device.resettable {
                 let mut child = Command::new(data.join("vfio-ubind")).arg(&device.slot).spawn().expect("failed to run vfio-ubind");
                 match child.wait() {
-                    Ok(status) => 
-                        if !status.success() {	
-                        panic!("vfio-ubind failed with {}! The device might not be bound to the vfio-driver and therefore not function correctly", status);
-                        },
-                    Err(err) => panic!("failed to wait on child. Got: {}", err)	
+                    Ok(status) if !status.success() => 
+                        panic!("vfio-ubind failed with {}! The device might not be bound to the vfio-driver and therefore not function correctly", status),
```
Comment (oberien) [inline windows-gaming-driver/src/driver/qemu.rs]: ~

**Review by oberien — COMMENTED** [review]
Finally spaces

File: windows-gaming-driver/src/setup/vfio.rs (hunk 54 above)
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: Reference #108

File: windows-gaming-driver/src/driver/qemu.rs [hunk 59]
```diff
@@ -118,7 +118,8 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
                 let mut child = Command::new(data.join("vfio-ubind")).arg(&device.slot).spawn().expect("failed to run vfio-ubind");
                 match child.wait() {
                     Ok(status) if !status.success() => 
-                        panic!("vfio-ubind failed with {}! The device might not be bound to the vfio-driver and therefore not function correctly", status),
+                        panic!("vfio-ubind failed with {}! \
+                                The device might not be bound to the vfio-driver and therefore not function correctly", status),
```
Comment (oberien) [inline windows-gaming-driver/src/driver/qemu.rs]: still too long. Sorry m8.

**Review by oberien — CHANGES_REQUESTED** [review]

File: windows-gaming-driver/src/driver/qemu.rs [hunk 60]
```diff
@@ -119,7 +119,11 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
                 match child.wait() {
                     Ok(status) if !status.success() => 
                         panic!("vfio-ubind failed with {}! \
-                                The device might not be bound to the vfio-driver and therefore not function correctly", status),
+                                The device might not be \
+                                bound to the \ 
+                                vfio-driver and \
+                                therefore not function \
+                                correctly", status),
```
Comment (oberien) [inline windows-gaming-driver/src/driver/qemu.rs]: I'll leave this up to @main--

**Review by oberien — DISMISSED** [review]

File: Makefile (hunk 25 above)
Comment (Ediacarium) [reply Makefile:19]: See #110 for this

File: windows-gaming-driver/src/driver/mod.rs [hunk 61]
```diff
@@ -96,10 +97,21 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
...
-    match core.run(qemu.select(joined)) {
-        Ok(((), _)) => (), // one (*hopefully* qemu) is done, so the other is too
-        Err((e, _)) => panic!("Unexpected error: {}", e),
+    core.run(qemu.join(joined.or_else(|x| { error!("Unexpected error: {}", x); Ok(()) }))).expect("Unexpected error");
+
+    info!("unbinding resettable vfio-things");
+    
+    for dev in cfg.machine.vfio_slots.iter() {
+        if dev.resettable {
+            let mut child = Command::new(data.join("vfio-ubind")).arg(&dev.slot).arg("-r").spawn().expect("failed to run vfio-ubind");
```
Comment (oberien) [inline windows-gaming-driver/src/driver/mod.rs]: I think you should plit this up into one line per function invocation.

File: windows-gaming-driver/src/driver/mod.rs [hunk 62]
```diff
@@ -96,10 +97,21 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
...
+            match child.wait() {
+                Ok(status) => 
+                        if !status.success() {
```
Comment (oberien) [inline windows-gaming-driver/src/driver/mod.rs]: Here again: inline the condition as match guard.

File: windows-gaming-driver/src/driver/qemu.rs [hunk 63]
```diff
@@ -112,9 +112,25 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
     trace!("setup usernet");
     qemu.args(&["-netdev", &usernet, "-device", "e1000,netdev=unet"]);
 
-    for slot in cfg.machine.vfio_slots.iter() {
-        qemu.args(&["-device", &format!("vfio-pci,host={},multifunction=on", slot)]);
-        debug!("Passed through {}", slot);
+    // TODO: Check if the configured device is in the configured slot
+    for device in cfg.machine.vfio_slots.iter() {
+        if device.resettable {
+                let mut child = Command::new(data.join("vfio-ubind")).arg(&device.slot).spawn().expect("failed to run vfio-ubind");
```
Comment (oberien) [inline windows-gaming-driver/src/driver/qemu.rs]: I think you should plit this up into one line per function invocation.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 64]
```diff
@@ -2,11 +2,14 @@ use std::borrow::Cow;
...
+use libudev::{Context, Enumerator};
 
-use config::{SetupConfig, MachineConfig};
-use setup::gpu;
+use config::{SetupConfig, MachineConfig, VfioDevice};
 use setup::ask;
 use setup::wizard;
+use pci_device::PciDevice;
+
+
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: 3 empty lines are 2 2 much

File: windows-gaming-driver/src/setup/vfio.rs [hunk 65]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+    let udev = Context::new().expect("Failed to create udev context");
+    let mut iter = Enumerator::new(&udev)?;
+    iter.match_subsystem("pci")?;
+    let pci_devs: Vec<_> = iter.scan_devices()?.map(PciDevice::new).collect();
+    
+    
+    // filter to the display controller class (0x03XXXX, udev drops the leading zero)
+    let gpus = pci_devs.iter().filter(|x| x.pci_class.starts_with("3") && x.pci_class.len() == 5).collect();
+    select_device(setup, machine, "Which graphics card would you like to pass through?", &gpus)?;
+    if ask::yesno("Do you want to pass aditional pci devices?") {
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "Would you like to"

File: windows-gaming-driver/src/setup/vfio.rs [hunk 66]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        println!("Add aditional pci devices (1/2)");
+        println!();
+        println!("Please choose aditional pci devices. These will be passed through to qemu on boot.");
+        println!("NOTE: The devices listed here can be reset. They will be bound to the vfio-pci driver on qemu's start and unbound when it quits");
+        println!("This should usually work. If it doesn't you're on your own.");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "If it doesn't, you'll be on your own" - get conditional clauses right ;)

File: windows-gaming-driver/src/setup/vfio.rs [hunk 67]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        println!("You will not be able to use these devices while qemu is running.");
+        println!("If the device you want to pass through is not resettable (like a gpu) it will show up in the next step.");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: `like a gpu` - But you already selected the GPU, so it won't show up in the next menu. Maybe find a better example here.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 68]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        println!("If you want a device permanently bound to vfio-pci for some reason select it in the next step.");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "for some reason, you'll need to" - get your conditional clauses right ;) Also, it'll be too long for a single line then.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 69]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        println!("MAKE SURE YOU DON'T PASS THROUGH YOUR USB-CONTROLLER TO WHICH YOUR KEYBOARD AND MOUSE IS CONNECTED!");
+        println!("Helpful tools to avoid this and figure out which numbers are which devices are lspci and lsusb with the -v, -t (lsusb only) and -nn (lspci only) command.");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: Split into multiple lines.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 70]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        println!();
+        let resetable_devices = pci_devs.iter().filter(|x| x.resettable).collect();
+        while let Ok(Some(())) = select_device(setup, machine, "Which device do you want to pass through?", &resetable_devices) {};
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "would you like to"

File: windows-gaming-driver/src/setup/vfio.rs [hunk 71]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        
+        println!("Add aditional pci devices (2/2)");
+        println!("");
+        println!("If you don't know what you are doing, choose None here!");
+        println!("NOTE: EVERY PCI DEVICE LISTED HERE WILL BE PERMANENTLY BOUND TO VFIO-PCI!");
+        println!("ONLY ADD DEVICES HERE IF YOU KNOW WHAT YOU ARE DOING!");
+        println!("If you kill your system using this there is only one thing i can say to you:");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "using this, there'll only be" - get your conditional clauses right ;)

File: windows-gaming-driver/src/setup/vfio.rs [hunk 72]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        println!();
+        println!("U done goofed m8.");
+        println!("Ur on ur own :)");
+        println!();
+        let all_devices = pci_devs.iter().filter(|x| x.pci_class != "60400").collect();
+        while let Ok(Some(())) = select_device(setup, machine, "Which device do you want to pass through?", &all_devices) {};
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: "would you like to"

File: windows-gaming-driver/src/setup/vfio.rs [hunk 73]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+    Ok(())	
+}
+
+fn select_device(setup: &mut SetupConfig, machine: &mut MachineConfig, question: &str, devices: &Vec<&PciDevice>) -> Result<Option<()>>{
+    let udev = Context::new().expect("Failed to create udev context");
+    let mut iter = Enumerator::new(&udev)?;
+    iter.match_subsystem("pci")?;
+    let udev_devices = iter.scan_devices()?.map(PciDevice::new);
+    let pci_devs: Vec<_> = udev_devices.filter(|x| !machine.vfio_slots.iter().any(|y| y.device == x.id)).collect();
+    let askable_devices: Vec<_> = devices.iter().filter(|x| !machine.vfio_slots.iter().any(|y| y.device == x.id)).collect();
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: Split into multiple lines. Each function (except for `.iter()`) into its own line.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 74]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+            };
+            
+            if !device.resettable {
+                setup.vfio_devs.push(device.id);
+            }
+            machine.vfio_slots.push(vfio_device);
+        }
+        Ok(Some(()))
+    }
+    else{
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: welp

File: windows-gaming-driver/src/util.rs [hunk 75]
```diff
@@ -22,4 +22,3 @@ pub fn usable_ports(bus: UsbBus) -> usize {
         UsbBus::Xhci => 15,
     }
 }
-
```
Comment (oberien) [inline windows-gaming-driver/src/util.rs:25]: ?

**Review by oberien — CHANGES_REQUESTED** [review]

File: Makefile (hunk 25 above)
Comment (main--) [reply Makefile:19]: So is this postponed now or what? It's just that the major reason why I would prefer doing it with workspaces is that we bridge make to cargo by always invoking cargo which gets weird/slow fast when we have 10 cargo invocations every time.

File: vfio-ubind/src/main.rs [hunk 76]
```diff
@@ -0,0 +1,112 @@
...
+use argparse::{ArgumentParser, StoreTrue, Store};
+use std::fs::{OpenOptions, self};
+use std::io::prelude::*;
+use users::os::unix::GroupExt;
+
+fn pretty_write(path: &Path, content: &str, dryrun: bool) {
+    if dryrun {
+        println!("writing {} into {}", content, path.display());
+    } else { 
+        info!("writing {} into {}", content, path.display());
```
Comment (main--) [inline vfio-ubind/src/main.rs]: see old review (why print vs info?)

File: vfio-ubind/src/main.rs [hunk 77]
```diff
@@ -0,0 +1,112 @@
...
+        ap.refer(&mut remove).add_option(&["-r", "--remove"], StoreTrue, "Reattach the default Driver to the device");
+        ap.parse_args_or_exit();
+    }
+    
+    env_logger::init().unwrap();
+    
+    debug!("effective uid: {} current uid: {}", users::get_effective_uid(), users::get_current_uid());
+    
+    if users::get_effective_uid() != 0 {
+        error!("This tool requires root permissions. If the setuid bit is not set, you need to execute this as root!");
```
Comment (main--) [inline vfio-ubind/src/main.rs]: No return/panic/anything? I'm sure you need to exit here.

File: vfio-ubind/src/main.rs [hunk 78]
```diff
@@ -0,0 +1,112 @@
...
+    if users::get_current_uid() != 0 {
+        let vfio_group = users::get_group_by_name("vfio")
+            .expect("Your system has no vfio group. You need to be part of it to run this tool!");
+        let user = users::get_user_by_uid(users::get_current_uid()).unwrap();
+        let user_name = user.name();
+        
+        if !vfio_group.members().contains(&user_name.to_owned()) {
+            panic!("You're not part of the vfio group. Apply there and run this tool again!");
+        }
+        else {
```
Comment (main--) [inline vfio-ubind/src/main.rs]: style nit

File: vfio-ubind/src/main.rs [hunk 79]
```diff
@@ -0,0 +1,112 @@
...
+    let bdf_regex = Regex::new(r"^[[:xdigit:]]{2}:[[:xdigit:]]{2}.[[:xdigit:]]$").unwrap();
+    
+    match (dbdf_regex.is_match(&device), bdf_regex.is_match(&device)) {
+        (false, true) => { 
+            warn!("No PCI domain supplied, assuming PCI domain is 0000");	
+            device = "0000:".to_string() + &device; 
+        },
+        (false, false) => panic!("Please supply Domain:Bus:Device.Function of PCI device in form: dddd:bb:dd.f"),
+        (true, _) => (),
+    }
```
Comment (main--) [inline vfio-ubind/src/main.rs]: again, get rid of those damn regexes, they accomplish nothing

File: vfio-ubind/src/main.rs [hunk 80]
```diff
@@ -0,0 +1,112 @@
...
+        info!("File {} didn't exist", dev_reset.display());
+        panic!("The device does not support resetting!");
+    }
+    
+    let dev_driver_link = dev_sysfs.join("driver");
+    let dev_driver = fs::read_link(dev_driver_link);
+    
+    if let Ok(driver) = dev_driver {
+        if driver.file_name().unwrap() == "vfio-pci" && !remove {
+            println!("Device already bound to vfio-pci driver, nothing to do here");
```
Comment (main--) [inline vfio-ubind/src/main.rs]: Why suddenly print (instead of logging)?

File: windows-gaming-driver/src/config.rs (hunk 35 above)
Comment (main--) [reply windows-gaming-driver/src/config.rs]: Actually, yeah: Please rename this now, this is a great opportunity as you have to rewrite your config anyways to switch to the struct. (We can't justify doing it later)

File: windows-gaming-driver/src/driver/mod.rs [hunk 81]
```diff
@@ -96,10 +97,21 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
...
 
-    match core.run(qemu.select(joined)) {
-        Ok(((), _)) => (), // one (*hopefully* qemu) is done, so the other is too
-        Err((e, _)) => panic!("Unexpected error: {}", e),
+    core.run(qemu.join(joined.or_else(|x| { error!("Unexpected error: {}", x); Ok(()) }))).expect("Unexpected error");
+
+    info!("unbinding resettable vfio-things");
+    
+    for dev in cfg.machine.vfio_slots.iter() {
+        if dev.resettable {
```
Comment (main--) [inline windows-gaming-driver/src/driver/mod.rs]: Please use `iter().filter()` instead of this `if`.

File: windows-gaming-driver/src/setup/vfio.rs (hunk 64 above)
Comment (main--) [reply windows-gaming-driver/src/setup/vfio.rs]: ???

File: windows-gaming-driver/src/setup/vfio.rs [hunk 82]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        println!("Please choose aditional pci devices. These will be passed through to qemu on boot.");
+        println!("NOTE: The devices listed here can be reset. They will be bound to the vfio-pci driver on qemu's start and unbound when it quits");
+        println!("This should usually work. If it doesn't you're on your own.");
+        println!("You will not be able to use these devices while qemu is running.");
+        println!("If the device you want to pass through is not resettable (like a gpu) it will show up in the next step.");
+        println!("If you want a device permanently bound to vfio-pci for some reason select it in the next step.");
+        println!("MAKE SURE YOU DON'T PASS THROUGH YOUR USB-CONTROLLER TO WHICH YOUR KEYBOARD AND MOUSE IS CONNECTED!");
+        println!("Helpful tools to avoid this and figure out which numbers are which devices are lspci and lsusb with the -v, -t (lsusb only) and -nn (lspci only) command.");
+        println!();
+        let resetable_devices = pci_devs.iter().filter(|x| x.resettable).collect();
```
Comment (main--) [inline windows-gaming-driver/src/setup/vfio.rs]: typo: resettable

File: windows-gaming-driver/src/setup/vfio.rs (hunk 70 above)
Comment (main--) [reply windows-gaming-driver/src/setup/vfio.rs]: `Option<()>` is `bool`. Just use the latter. Also, you're not supposed these errors - they come straight from udev and are thus fatal. Just do this:

```rust
while select_device(setup, machine, "...", &resettable_devices).expect("...") { }
```

(Also, the trailing `;` is wrong.)

File: windows-gaming-driver/src/setup/vfio.rs [hunk 83]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        while let Ok(Some(())) = select_device(setup, machine, "Which device do you want to pass through?", &all_devices) {};
+    }
+    Ok(())	
+}
+
+fn select_device(setup: &mut SetupConfig, machine: &mut MachineConfig, question: &str, devices: &Vec<&PciDevice>) -> Result<Option<()>>{
+    let udev = Context::new().expect("Failed to create udev context");
+    let mut iter = Enumerator::new(&udev)?;
+    iter.match_subsystem("pci")?;
+    let udev_devices = iter.scan_devices()?.map(PciDevice::new);
```
Comment (main--) [inline windows-gaming-driver/src/setup/vfio.rs]: ???????????????????

ffs why are you re-querying these?

File: windows-gaming-driver/src/setup/vfio.rs [hunk 84]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        println!("You will not be able to use these devices while qemu is running.");
+        println!("If the device you want to pass through is not resettable (like a gpu) it will show up in the next step.");
+        println!("If you want a device permanently bound to vfio-pci for some reason select it in the next step.");
+        println!("MAKE SURE YOU DON'T PASS THROUGH YOUR USB-CONTROLLER TO WHICH YOUR KEYBOARD AND MOUSE IS CONNECTED!");
+        println!("Helpful tools to avoid this and figure out which numbers are which devices are lspci and lsusb with the -v, -t (lsusb only) and -nn (lspci only) command.");
+        println!();
+        let resetable_devices = pci_devs.iter().filter(|x| x.resettable).collect();
+        while let Ok(Some(())) = select_device(setup, machine, "Which device do you want to pass through?", &resetable_devices) {};
+        
+        println!("Add aditional pci devices (2/2)");
```
Comment (main--) [inline windows-gaming-driver/src/setup/vfio.rs]: *sigh*

I told you to hide this and only show it to users that *specifically* request to see it.

Please.

Even if it's just another yesno around this thing.

Hide it.

File: windows-gaming-driver/src/setup/vfio.rs (hunk 72 above)
Comment (main--) [reply windows-gaming-driver/src/setup/vfio.rs]: ~

File: windows-gaming-driver/src/setup/vfio.rs [hunk 85]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+        println!("U done goofed m8.");
+        println!("Ur on ur own :)");
+        println!();
+        let all_devices = pci_devs.iter().filter(|x| x.pci_class != "60400").collect();
+        while let Ok(Some(())) = select_device(setup, machine, "Which device do you want to pass through?", &all_devices) {};
+    }
+    Ok(())	
+}
+
+fn select_device(setup: &mut SetupConfig, machine: &mut MachineConfig, question: &str, devices: &Vec<&PciDevice>) -> Result<Option<()>>{
```
Comment (main--) [inline windows-gaming-driver/src/setup/vfio.rs]: `&Vec<T>` is rarely useful, you should basically always use `&[T]` instead.

---

I wish you got rid of `setup.vfio_devs` in this PR instead of postponing it for someone else to do.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 86]
```diff
@@ -79,6 +82,87 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+    let udev = Context::new().expect("Failed to create udev context");
+    let mut iter = Enumerator::new(&udev)?;
+    iter.match_subsystem("pci")?;
+    let udev_devices = iter.scan_devices()?.map(PciDevice::new);
+    let pci_devs: Vec<_> = udev_devices.filter(|x| !machine.vfio_slots.iter().any(|y| y.device == x.id)).collect();
+    let askable_devices: Vec<_> = devices.iter().filter(|x| !machine.vfio_slots.iter().any(|y| y.device == x.id)).collect();
+    
+    println!("{}", devices.len());
```
Comment (main--) [inline windows-gaming-driver/src/setup/vfio.rs]: ?

**Review by main-- — CHANGES_REQUESTED** [review]

File: windows-gaming-driver/src/driver/mod.rs [hunk 87]
```diff
@@ -96,10 +97,21 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
         Box::new(catch_sigterm),
     ]).map(|_| ());
 
-    match core.run(qemu.select(joined)) {
-        Ok(((), _)) => (), // one (*hopefully* qemu) is done, so the other is too
-        Err((e, _)) => panic!("Unexpected error: {}", e),
+    core.run(qemu.join(joined.or_else(|x| { error!("Unexpected error: {}", x); Ok(()) }))).expect("Unexpected error");
```
Comment (main--) [inline windows-gaming-driver/src/driver/mod.rs]: ijkolnufuahcdcjhnixckgfdxcgijkofgdcsuijohfcgduijohfurgdsijohfgcrdsijohl

Comment (main--) [reply windows-gaming-driver/src/driver/mod.rs]:
```rust
core.run(qemu.select2(joined).then(|x| {
    match x {
        Ok(Either::A((x, _))) => info!("qemu down first, all ok"),
        Err(Either::A((e, _))) => error!("..."),
        Ok(Either::B((_, _))) => unreachable!(), // we never return cleanly
        Err(Either::B((e, a))) => {
            error!("...");
            return a.boxed(); // we errored first, wait for qemu to exit
        }
    }
    future::ok(()).boxed()
)).expect("...");
```

File: windows-gaming-driver/src/setup/vfio.rs [hunk 88]
```diff
@@ -82,82 +82,69 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
     println!("[{}]\tNone of the above.", askable_devices.len());
 
     let selection = ask::numeric(question, 0..askable_devices.len()+1);
-    
-    if selection < askable_devices.len() {
-        let selected = &askable_devices[selection];
-        for device in pci_devs.iter().filter(|x| x.pci_device() == selected.pci_device()) {
+
+    if let Some(selected_id) = askable_devices.get(selection).map(|x| x.id) {
+        for device in devices.iter().filter(|x| x.id == selected_id) {
```
Comment (Ediacarium) [inline windows-gaming-driver/src/setup/vfio.rs]: This does not do what you think it does. This check for the specific id. However the graphics and audio part of a gpu have different ids: 
> NVIDIA Corporation Unknown model [10de:1b06]
> NVIDIA Corporation GP102 HDMI Audio Controller [10de:10ef]

File: vfio-ubind/src/main.rs [hunk 89]
```diff
@@ -57,8 +57,10 @@ fn main() {
         }
     }
 
-    let dev_sysfs = Path::new("/sys/bus/pci/devices/").join(&device);
-    assert!(dev_sysfs.exists(), "The given device does not exist!");
+    let devices_folder = Path::new("/sys/bus/pci/devices/");
+    let dev_sysfs = devices_folder.join(&device).canonicalize()
+        .expect("Failed to look up the given device (does it exist?)!");
+    assert_eq!(dev_sysfs.parent(), Some(devices_folder));
```
Comment (Ediacarium) [inline vfio-ubind/src/main.rs]: > windows-gaming-driver[4091]: thread 'main' panicked at 'assertion failed: `(left == right)` (left: `Some("/sys/devices/pci0000:00/0000:00:1c.4")`, right: `Some("/sys/bus/pci/devices/")`)', src/main.rs:63

Comment (main--) [reply vfio-ubind/src/main.rs]: we lost

File: Makefile (hunk 25 above)
Comment (oberien) [reply Makefile:19]: Postponed with #110

File: vfio-ubind/src/main.rs [hunk 90]
```diff
@@ -0,0 +1,97 @@
...
+    let dev_sysfs = Path::new("/sys/bus/pci/devices/").read_dir().unwrap()
+        .map(Result::unwrap).find(|x| x.file_name() == *device).map(|x| x.path())
+        .expect("Failed to look up the given device (does it exist?)!");
+    let dev_iommu = dev_sysfs.join("iommu");
+    
+    if !dev_iommu.exists() {
+        info!("File {} didn't exist", dev_iommu.display());
+        panic!("No signs of an IOMMU. \
+                Check your hardware and/or linux cmdline parameters. \
+                Use intel_iommu=on or iommu=pt iommu=1");
```
Comment (oberien) [inline vfio-ubind/src/main.rs]:
```
Use `intel_iommu=on` or `iommu=pt iommu=1`"
```

File: windows-gaming-driver/src/driver/qemu.rs [hunk 91]
```diff
@@ -115,9 +115,25 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
     trace!("setup usernet");
     qemu.args(&["-netdev", &usernet, "-device", "e1000,netdev=unet"]);
 
-    for slot in cfg.machine.vfio_slots.iter() {
-        qemu.args(&["-device", &format!("vfio-pci,host={},multifunction=on", slot)]);
-        debug!("Passed through {}", slot);
+    // TODO: Check if the configured device is in the configured slot
+    for device in cfg.machine.pci_devices.iter() {
+        if device.resettable {
+                let mut child = Command::new(data.join("vfio-ubind")).arg(&device.slot).spawn().expect("failed to run vfio-ubind");
```
Comment (oberien) [inline windows-gaming-driver/src/driver/qemu.rs]: Indentation

File: windows-gaming-driver/src/driver/qemu.rs [hunk 92]
```diff
@@ -115,9 +115,25 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path, clientpipe_path: &Path, monito
...
+                match child.wait() {
+                    Ok(status) if !status.success() => 
+                        panic!("vfio-ubind failed with {}! \
+                                The device might not be \
+                                bound to the \
+                                vfio-driver and \
+                                therefore not function \
+                                correctly", status),
```
Comment (oberien) [inline windows-gaming-driver/src/driver/qemu.rs]: ¯\_(ツ)_/¯

File: windows-gaming-driver/src/config.rs [hunk 93]
```diff
@@ -252,6 +250,13 @@ pub struct StorageDevice {
 }
 
 #[derive(Deserialize, Serialize, Debug, Clone)]
+pub struct VfioDevice {
+    pub resettable: bool,
+    pub slot: String,
+    pub device: PciId,
```
Comment (oberien) [inline windows-gaming-driver/src/config.rs]: `VfioDevice.device` feels weird, I guess `VfioDevice.id` would be better.

File: windows-gaming-driver/src/setup/vfio.rs (hunk 64 above)
Comment (oberien) [reply windows-gaming-driver/src/setup/vfio.rs]: Still a problem.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 94]
```diff
@@ -79,6 +82,75 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+                                |x| !x.resettable && x.pci_class != "60400")? { }
+        }
+    }
+    Ok(())
+}
+
+fn select_device<P: Fn(&PciDevice) -> bool>(machine: &mut MachineConfig,
+                                            question: &str,
+                                            devices: &[PciDevice],
+                                            predicate: P) -> Result<bool> {
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: Use a `where` here and put multiple arguments in the same line.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 95]
```diff
@@ -79,6 +82,75 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+    for (i, dev) in askable_devices.iter().enumerate() {
+        println!("[{}]\t{}", i, dev);
+    }
+    println!("[{}]\tNone of the above.", askable_devices.len());
+
+    let selection = ask::numeric(question, 0..askable_devices.len()+1);
+
+    if let Some(selected_slot) = askable_devices.get(selection).map(|x| x.pci_slot.clone()) {
+        for device in devices.iter()
+            .filter(|x| x.pci_slot[..x.pci_slot.len()-1] == selected_slot[..selected_slot.len()-1]) {
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: `selected_slot[..selected_slot.len()-1]` is the same as `selected_slot[..]`. Then it can also be all in the same line.

File: windows-gaming-driver/src/setup/vfio.rs [hunk 96]
```diff
@@ -79,6 +82,75 @@ pub fn setup(setup: &mut SetupConfig, machine: &mut MachineConfig) -> bool {
...
+    iter.match_subsystem("pci")?;
+    let pci_devs: Vec<_> = iter.scan_devices()?.map(PciDevice::new).collect();
+
+
+    // filter to the display controller class (0x03XXXX, udev drops the leading zero)
+    select_device(machine, "Which graphics card would you like to pass through?", &pci_devs,
+                  |x| x.pci_class.starts_with("3") && x.pci_class.len() == 5)?;
+    if ask::yesno("Would you like to pass aditional PCI devices?") {
+        println!();
+        println!("Please choose aditional pci devices. These will be passed through to the VM on boot.");
```
Comment (oberien) [inline windows-gaming-driver/src/setup/vfio.rs]: `on boot` is ambiguous as it could mean both windows boot and linux boot.

File: windows-gaming-driver/src/util.rs (hunk 75 above)
Comment (oberien) [reply windows-gaming-driver/src/util.rs:25]: Still an issue

**Review by oberien — CHANGES_REQUESTED** [review]

File: windows-gaming-driver/src/setup/vfio.rs (hunk 95 above)
Comment (oberien) [reply windows-gaming-driver/src/setup/vfio.rs]: Actually it's not. It strips away the last byte.

File: windows-gaming-driver/src/config.rs (hunk 93 above)
Comment (Ediacarium) [reply windows-gaming-driver/src/config.rs]: This is what it would currently look like in the config:
(Assuming github would respect the indentation)

>   pci_devices: 
>     - 
>       resettable: false
>       slot: "0000:02:00.0"
>       device: 
>         vendor: 4318
>         device: 6918

Having 

>   pci_devices: 
>     - 
>       resettable: false
>       slot: "0000:02:00.0"
>       id: 
>         vendor: 4318
>         device: 6918

feels strange to me as well

File: windows-gaming-driver/src/setup/vfio.rs (hunk 96 above)
Comment (Ediacarium) [reply windows-gaming-driver/src/setup/vfio.rs]: Well how should something be passed to the vm on (linux) boot when the vm is not running?

Although we could indeed word it better.

**Review by oberien — DISMISSED** [review]

**Review by oberien — DISMISSED** [review]

File: vfio-ubind/.gitignore [hunk 97]
```diff
@@ -0,0 +1,10 @@
+# Generated by Cargo
+# will have compiled files and executables
+/target/
+
+# These are backup files generated by rustfmt
+**/*.rs.bk
+
+# vim swap files
```
Comment (main--) [inline vfio-ubind/.gitignore]: might wanna get this shit out of the way one day (not lang-dependent so I moved it to the root gitignore)

File: windows-gaming-driver/src/driver/mod.rs [hunk 98]
```diff
@@ -138,10 +139,28 @@ pub fn run(cfg: &Config, tmp: &Path, data: &Path) {
         Box::new(clipboard_reader),
     ]).map(|_| ());
 
-    match core.run(qemu.select(joined)) {
-        Ok(((), _)) => (), // one (*hopefully* qemu) is done, so the other is too
-        Err((e, _)) => panic!("Unexpected error: {}", e),
+    core.run(qemu.select2(joined).then(|x| {
+        match x {
+            Ok(future::Either::A((_, _))) => info!("qemu down first, all ok"),
+            Err(future::Either::A((e, _))) => return future::err(e).boxed(),//error!("Waiting for qemu errored: {}", e),
```
Comment (main--) [inline windows-gaming-driver/src/driver/mod.rs]: wtf did I commit this???

**Review by main-- — CHANGES_REQUESTED** [review]
the one comment doesn't belong there, rest looking great

**Review by main-- — APPROVED** [review]

**Review by oberien — APPROVED** [review]
